In [1]:
import sqlite3
import pandas as pd
import nbimporter

In [2]:
from final_scores import calculate_final_driver_places 

conn = sqlite3.connect('formula1.db')

drivers_final_positions = calculate_final_driver_places(conn)

print(drivers_final_positions)

      year  driverId      driver_name  points  place
73    1950       642      Nino Farina    30.0      1
66    1950       579      Juan Fangio    27.0      2
72    1950       786    Luigi Fagioli    24.0      3
70    1950       627     Louis Rosier    13.0      4
56    1950       647   Alberto Ascari    11.0      5
...    ...       ...              ...     ...    ...
3133  2022       855      Guanyu Zhou     6.0     18
3136  2022       848  Alexander Albon     4.0     19
3139  2022       849  Nicholas Latifi     2.0     20
3145  2022       856    Nyck de Vries     2.0     20
3140  2022       807  Nico HÃ¼lkenberg     0.0     22

[3146 rows x 5 columns]

In [3]:
lap_times_query = """
    SELECT
        d.driverId,
        r.year,
        MIN((CAST(lt.milliseconds AS FLOAT) - fl.fastest_lap) / fl.fastest_lap * 100.0) AS min_lap_time_diff,
        AVG((CAST(lt.milliseconds AS FLOAT) - fl.fastest_lap) / fl.fastest_lap * 100.0) AS avg_lap_time_diff,
        MAX((CAST(lt.milliseconds AS FLOAT) - fl.fastest_lap) / fl.fastest_lap * 100.0) AS max_lap_time_diff
    FROM
        lap_times lt
        JOIN drivers d ON lt.driverId = d.driverId
        JOIN races r ON lt.raceId = r.raceId
        JOIN (
            SELECT
                lt.raceId,
                MIN(lt.milliseconds) AS fastest_lap
            FROM
                lap_times lt
            GROUP BY
                lt.raceId
        ) fl ON lt.raceId = fl.raceId
    WHERE
        r.year != 2023
    GROUP BY
        d.driverId,
        r.year;
"""
lap_times_stats = pd.read_sql_query(lap_times_query, conn)

In [4]:
median_lap_position = '''
WITH RankedLaps AS (
    SELECT
        lt.driverId,
        r.year,
        lt.position,
        ROW_NUMBER() OVER (PARTITION BY lt.driverId, r.year ORDER BY lt.position) AS row_num,
        COUNT(*) OVER (PARTITION BY lt.driverId, r.year) AS total_count
    FROM
        lap_times lt
    JOIN
        races r ON lt.raceId = r.raceId
    WHERE
        r.date != '2023'
),
MedianCandidates AS (
    SELECT
        driverId,
        year,
        AVG(position) AS median_candidate
    FROM
        RankedLaps
    WHERE
        row_num = (total_count + 1) / 2 OR row_num = (total_count + 2) / 2
    GROUP BY
        driverId, year
)
SELECT
    driverId,
    year,
    AVG(median_candidate) AS median_lap_position
FROM
    MedianCandidates
GROUP BY
    driverId, year;

'''

df = pd.read_sql_query(median_lap_position, conn)

lap_times_stats = pd.merge(lap_times_stats, df, on=['driverId', 'year'], how='left')

print(lap_times_stats)

     driverId  year  min_percentage_difference  avg_percentage_difference  \
0           1  2007                   0.000000                   7.852700
1           1  2008                   0.000000                   7.666610
2           1  2009                   0.074346                   6.171578
3           1  2010                   0.000000                  10.709896
4           1  2011                   0.000000                   8.270089
..        ...   ...                        ...                        ...
642       853  2021                   2.817997                  21.635194
643       854  2021                   2.234354                  18.256438
644       854  2022                   0.704944                  14.242761
645       855  2022                   0.000000                  12.770114
646       856  2022                   3.086993                   8.555862

     max_percentage_difference  median_lap_position
0                  1465.791089                  2.0
1                   101.287948                  3.0
2                    79.374498                  7.0
3                  2567.450593                  4.0
4                  1600.104940                  4.0
..                         ...                  ...
642                2443.049302                 18.0
643                2428.528386                 18.0
644                3432.659375                 14.0
645                1625.453523                 14.0
646                  46.221588                  9.0

[647 rows x 6 columns]

In [5]:
laps_driven_query = f'''
        SELECT
            lt.driverId,
            r.year,
            COUNT(*) AS laps_driven
        FROM
            lap_times lt
        JOIN
            races r ON lt.raceId = r.raceId
        WHERE
            r.year != '2023'
        GROUP BY
            lt.driverId, r.year;
    '''
df = pd.read_sql_query(laps_driven_query, conn)

lap_times_stats = pd.merge(lap_times_stats, df, on=['driverId', 'year'], how='left')

print(lap_times_stats)

     driverId  year  min_percentage_difference  avg_percentage_difference  \
0           1  2007                   0.000000                   7.852700
1           1  2008                   0.000000                   7.666610
2           1  2009                   0.074346                   6.171578
3           1  2010                   0.000000                  10.709896
4           1  2011                   0.000000                   8.270089
..        ...   ...                        ...                        ...
642       853  2021                   2.817997                  21.635194
643       854  2021                   2.234354                  18.256438
644       854  2022                   0.704944                  14.242761
645       855  2022                   0.000000                  12.770114
646       856  2022                   3.086993                   8.555862

     max_percentage_difference  median_lap_position  laps_driven
0                  1465.791089                  2.0         1037
1                   101.287948                  3.0         1065
2                    79.374498                  7.0          904
3                  2567.450593                  4.0         1001
4                  1600.104940                  4.0         1013
..                         ...                  ...          ...
642                2443.049302                 18.0         1008
643                2428.528386                 18.0         1135
644                3432.659375                 14.0         1142
645                1625.453523                 14.0         1060
646                  46.221588                  9.0           53

[647 rows x 7 columns]

In [6]:
def calculate_pit_stop_stats(connection):
    # Query to calculate fastest pit stops and differences
    pit_stop_query = """
    WITH FastestPitStops AS (
        SELECT
            ps.raceId,
            MIN(ps.milliseconds) AS fastest_pit_stop
        FROM
            pit_stops ps
        GROUP BY
            ps.raceId
    )

    SELECT
        ps.raceId,
        ps.driverId,
        r.year,
        ps.milliseconds AS pit_stop_time,
        fps.fastest_pit_stop,
        (ps.milliseconds - fps.fastest_pit_stop) AS difference,
        (CAST(ps.milliseconds AS FLOAT) - fps.fastest_pit_stop) / fps.fastest_pit_stop * 100.0 AS percentage_difference
    FROM
        pit_stops ps
        JOIN FastestPitStops fps ON ps.raceId = fps.raceId
        JOIN races r ON ps.raceId = r.raceId
    WHERE
        strftime('%Y', r.date) <> '2023'
    """

    # Read the query results into a DataFrame
    pit_stop_df = pd.read_sql_query(pit_stop_query, connection)

    # Calculate min, avg, and max for each driver and year
    pit_stop_stats_df = pit_stop_df.groupby(['driverId', 'year']).agg(
        min_percentage_difference=pd.NamedAgg(column='percentage_difference', aggfunc='min'),
        avg_percentage_difference=pd.NamedAgg(column='percentage_difference', aggfunc='mean'),
        max_percentage_difference=pd.NamedAgg(column='percentage_difference', aggfunc='max')
    ).reset_index()

    return pit_stop_stats_df


pit_stop_stats = calculate_pit_stop_stats(conn)
print(pit_stop_stats)

     driverId  year  min_percentage_difference  avg_percentage_difference  \
0           1  2011                   0.000000                  30.862876
1           1  2012                   0.000000                  39.127907
2           1  2013                   0.265298                  20.120236
3           1  2014                   0.987032                 131.604073
4           1  2015                   0.000000                  13.673431
..        ...   ...                        ...                        ...
270       853  2021                   0.455934                 889.060424
271       854  2021                   0.841363                 848.779654
272       854  2022                   1.223789                 324.143796
273       855  2022                   0.000000                 192.305111
274       856  2022                   5.704107                   5.704107

     max_percentage_difference
0                   156.287253
1                   112.026741
2                    65.973164
3                  4751.320224
4                    68.839476
..                         ...
270               12190.605470
271               13435.219407
272               10786.783875
273                4710.664099
274                   5.704107

[275 rows x 5 columns]

In [7]:
query = '''
    WITH MostCommonPitStopLap AS (
        SELECT
            drivers.driverId,
            races.year,
            pit_stops.lap AS most_common_pitstop_lap,
            ROW_NUMBER() OVER (PARTITION BY drivers.driverId, races.year ORDER BY COUNT(pit_stops.lap) DESC) AS lap_rank
        FROM
            drivers
        JOIN
            pit_stops ON drivers.driverId = pit_stops.driverId
        JOIN
            races ON pit_stops.raceId = races.raceId
        WHERE
            races.year != '2023'
        GROUP BY
            drivers.driverId, races.year, pit_stops.lap
    )
    SELECT
        driverId,
        year,
        most_common_pitstop_lap
    FROM
        MostCommonPitStopLap
    WHERE
        lap_rank = 1;
'''

df = pd.read_sql_query(query, conn)

pit_stop_stats = pd.merge(pit_stop_stats, df, on=['driverId', 'year'], how='left')


print(pit_stop_stats)

     driverId  year  min_percentage_difference  avg_percentage_difference  \
0           1  2011                   0.000000                  30.862876
1           1  2012                   0.000000                  39.127907
2           1  2013                   0.265298                  20.120236
3           1  2014                   0.987032                 131.604073
4           1  2015                   0.000000                  13.673431
..        ...   ...                        ...                        ...
270       853  2021                   0.455934                 889.060424
271       854  2021                   0.841363                 848.779654
272       854  2022                   1.223789                 324.143796
273       855  2022                   0.000000                 192.305111
274       856  2022                   5.704107                   5.704107

     max_percentage_difference  most_common_pitstop_lap
0                   156.287253                       16
1                   112.026741                       36
2                    65.973164                       31
3                  4751.320224                       26
4                    68.839476                       13
..                         ...                      ...
270               12190.605470                       31
271               13435.219407                       34
272               10786.783875                       14
273                4710.664099                        9
274                   5.704107                       19

[275 rows x 6 columns]

In [8]:
query = """
    SELECT races.year, r.driverId, r.constructorId
    FROM results r
    JOIN races ON r.raceId = races.raceId
    WHERE races.year <> 2023
    GROUP BY r.driverId, races.year, r.constructorId;
"""
constructors_per_driver = pd.read_sql_query(query, conn)

In [9]:
drivers_with_constructors = pd.merge(drivers_final_positions, constructors_per_driver, on=['driverId', 'year'], how='left')
print(drivers_with_constructors)

      year  driverId      driver_name  points  place  constructorId
0     1950       642      Nino Farina    30.0      1             51
1     1950       579      Juan Fangio    27.0      2             51
2     1950       786    Luigi Fagioli    24.0      3             51
3     1950       627     Louis Rosier    13.0      4            154
4     1950       647   Alberto Ascari    11.0      5              6
...    ...       ...              ...     ...    ...            ...
3482  2022       855      Guanyu Zhou     6.0     18             51
3483  2022       848  Alexander Albon     4.0     19              3
3484  2022       849  Nicholas Latifi     2.0     20              3
3485  2022       856    Nyck de Vries     2.0     20              3
3486  2022       807  Nico HÃ¼lkenberg     0.0     22            117

[3487 rows x 6 columns]

In [10]:
constructor_points_query = '''
    WITH LastRacePerSeason AS (
        SELECT
            r.year,
            MAX(r.date) AS last_race_date
        FROM
            races r
        WHERE
            r.year BETWEEN 1950 AND 2022
        GROUP BY
            r.year
    ),
    ConstructorStandingsWithRank AS (
        SELECT
            lrs.year,
            cs.constructorId,
            c.name AS constructor_name,
            cs.points AS constructor_points,
            RANK() OVER (PARTITION BY lrs.year ORDER BY cs.points DESC) AS constructor_place
        FROM
            LastRacePerSeason lrs
        JOIN
            races r ON lrs.year = r.year AND lrs.last_race_date = r.date
        JOIN
            constructor_standings cs ON r.raceId = cs.raceId
        JOIN
            constructors c ON cs.constructorId = c.constructorId
    )

    SELECT
        *,
        SUM(CASE WHEN constructor_place = 1 THEN 1 ELSE 0 END) OVER (PARTITION BY constructorId ORDER BY year) AS times_first_place
    FROM
        ConstructorStandingsWithRank
    ORDER BY
        year DESC, constructor_points DESC;
'''

# Execute the query and fetch the results into a DataFrame
constructor_points_df = pd.read_sql_query(constructor_points_query, conn)


# Display the result
print(constructor_points_df)

     year  constructorId constructor_name  constructor_points  \
0    2022              9         Red Bull               759.0
1    2022              6          Ferrari               554.0
2    2022            131         Mercedes               515.0
3    2022            214   Alpine F1 Team               173.0
4    2022              1          McLaren               159.0
..    ...            ...              ...                 ...
895  1958            105         Maserati                 6.0
896  1958             32       Team Lotus                 3.0
897  1958             95          Porsche                 0.0
898  1958            125        Connaught                 0.0
899  1958            127             OSCA                 0.0

     constructor_place  times_first_place
0                    1                  5
1                    2                 15
2                    3                  8
3                    4                  0
4                    5                  9
..                 ...                ...
895                  5                  0
896                  6                  0
897                  7                  0
898                  7                  0
899                  7                  0

[900 rows x 6 columns]

In [11]:
drivers_with_constructors = pd.merge(drivers_with_constructors, constructor_points_df, on=['year', 'constructorId'], how='left')

print(drivers_with_constructors)

      year  driverId      driver_name  points  place  constructorId  \
0     1950       642      Nino Farina    30.0      1             51
1     1950       579      Juan Fangio    27.0      2             51
2     1950       786    Luigi Fagioli    24.0      3             51
3     1950       627     Louis Rosier    13.0      4            154
4     1950       647   Alberto Ascari    11.0      5              6
...    ...       ...              ...     ...    ...            ...
3482  2022       855      Guanyu Zhou     6.0     18             51
3483  2022       848  Alexander Albon     4.0     19              3
3484  2022       849  Nicholas Latifi     2.0     20              3
3485  2022       856    Nyck de Vries     2.0     20              3
3486  2022       807  Nico HÃ¼lkenberg     0.0     22            117

     constructor_name  constructor_points  constructor_place  \
0                 NaN                 NaN                NaN
1                 NaN                 NaN                NaN
2                 NaN                 NaN                NaN
3                 NaN                 NaN                NaN
4                 NaN                 NaN                NaN
...               ...                 ...                ...
3482       Alfa Romeo                55.0                6.0
3483         Williams                 8.0               10.0
3484         Williams                 8.0               10.0
3485         Williams                 8.0               10.0
3486     Aston Martin                55.0                6.0

      times_first_place
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
...                 ...
3482                0.0
3483                9.0
3484                9.0
3485                9.0
3486                0.0

[3487 rows x 10 columns]

In [12]:
lap_pit_df = pd.merge(lap_times_stats, pit_stop_stats, on=['driverId', 'year'], how='outer', suffixes=('_lap', '_pit'))

lap_pit_df = lap_pit_df.fillna('unknown')

print(lap_pit_df)

     driverId  year  min_percentage_difference_lap  \
0           1  2007                       0.000000
1           1  2008                       0.000000
2           1  2009                       0.074346
3           1  2010                       0.000000
4           1  2011                       0.000000
..        ...   ...                            ...
642       853  2021                       2.817997
643       854  2021                       2.234354
644       854  2022                       0.704944
645       855  2022                       0.000000
646       856  2022                       3.086993

     avg_percentage_difference_lap  max_percentage_difference_lap  \
0                         7.852700                    1465.791089
1                         7.666610                     101.287948
2                         6.171578                      79.374498
3                        10.709896                    2567.450593
4                         8.270089                    1600.104940
..                             ...                            ...
642                      21.635194                    2443.049302
643                      18.256438                    2428.528386
644                      14.242761                    3432.659375
645                      12.770114                    1625.453523
646                       8.555862                      46.221588

     median_lap_position  laps_driven min_percentage_difference_pit  \
0                    2.0         1037                       unknown
1                    3.0         1065                       unknown
2                    7.0          904                       unknown
3                    4.0         1001                       unknown
4                    4.0         1013                           0.0
..                   ...          ...                           ...
642                 18.0         1008                      0.455934
643                 18.0         1135                      0.841363
644                 14.0         1142                      1.223789
645                 14.0         1060                           0.0
646                  9.0           53                      5.704107

    avg_percentage_difference_pit max_percentage_difference_pit  \
0                         unknown                       unknown
1                         unknown                       unknown
2                         unknown                       unknown
3                         unknown                       unknown
4                       30.862876                    156.287253
..                            ...                           ...
642                    889.060424                   12190.60547
643                    848.779654                  13435.219407
644                    324.143796                  10786.783875
645                    192.305111                   4710.664099
646                      5.704107                      5.704107

    most_common_pitstop_lap
0                   unknown
1                   unknown
2                   unknown
3                   unknown
4                      16.0
..                      ...
642                    31.0
643                    34.0
644                    14.0
645                     9.0
646                    19.0

[647 rows x 11 columns]

In [13]:
final_df = pd.merge(drivers_with_constructors, lap_pit_df, on=['driverId', 'year'], how='outer')

final_df = final_df.fillna('unknown')

print(final_df)

final_df.to_csv('FINAL.csv', index=False)

      year  driverId      driver_name   points    place constructorId  \
0     1950       642      Nino Farina     30.0      1.0          51.0
1     1950       579      Juan Fangio     27.0      2.0          51.0
2     1950       786    Luigi Fagioli     24.0      3.0          51.0
3     1950       627     Louis Rosier     13.0      4.0         154.0
4     1950       647   Alberto Ascari     11.0      5.0           6.0
...    ...       ...              ...      ...      ...           ...
3486  2022       807  Nico HÃ¼lkenberg      0.0     22.0         117.0
3487  2002        19          unknown  unknown  unknown       unknown
3488  2007        28          unknown  unknown  unknown       unknown
3489  1996        58          unknown  unknown  unknown       unknown
3490  1999        72          unknown  unknown  unknown       unknown

     constructor_name constructor_points constructor_place times_first_place  \
0             unknown            unknown           unknown           unknown
1             unknown            unknown           unknown           unknown
2             unknown            unknown           unknown           unknown
3             unknown            unknown           unknown           unknown
4             unknown            unknown           unknown           unknown
...               ...                ...               ...               ...
3486     Aston Martin               55.0               6.0               0.0
3487          unknown            unknown           unknown           unknown
3488          unknown            unknown           unknown           unknown
3489          unknown            unknown           unknown           unknown
3490          unknown            unknown           unknown           unknown

     min_percentage_difference_lap avg_percentage_difference_lap  \
0                          unknown                       unknown
1                          unknown                       unknown
2                          unknown                       unknown
3                          unknown                       unknown
4                          unknown                       unknown
...                            ...                           ...
3486                      2.201148                     11.013943
3487                      4.120356                      8.499973
3488                     10.694323                    154.153008
3489                       3.92784                     13.236229
3490                      3.539925                      5.685171

     max_percentage_difference_lap median_lap_position laps_driven  \
0                          unknown             unknown     unknown
1                          unknown             unknown     unknown
2                          unknown             unknown     unknown
3                          unknown             unknown     unknown
4                          unknown             unknown     unknown
...                            ...                 ...         ...
3486                     72.513478                16.0       107.0
3487                     39.237865                18.0        75.0
3488                   1448.359234                 8.0        13.0
3489                    115.997674                16.0        33.0
3490                     21.511065                14.0        31.0

     min_percentage_difference_pit avg_percentage_difference_pit  \
0                          unknown                       unknown
1                          unknown                       unknown
2                          unknown                       unknown
3                          unknown                       unknown
4                          unknown                       unknown
...                            ...                           ...
3486                      6.515534                     18.020759
3487                       unknown                       unknown
3488                       unknown                       unknown
3489                       unknown                       unknown
3490                       unknown                       unknown

     max_percentage_difference_pit most_common_pitstop_lap
0                          unknown                 unknown
1                          unknown                 unknown
2                          unknown                 unknown
3                          unknown                 unknown
4                          unknown                 unknown
...                            ...                     ...
3486                     41.859233                    37.0
3487                       unknown                 unknown
3488                       unknown                 unknown
3489                       unknown                 unknown
3490                       unknown                 unknown

[3491 rows x 19 columns]